/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPayment__factory } from "./IPayment__factory";
export { Payment__factory } from "./Payment__factory";
